[build]
  command = "cd client && npm ci --legacy-peer-deps && npm run build"
  publish = "client/dist"

# Rule for router history mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
