const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const html = fs.readFileSync('client/public/seat-mapper.html', 'utf8');
const script = html.match(/<script>([\s\S]*?)<\/script>/)[1];
const frames = [];
let renders = 0;
const context2d = new Proxy({}, {get: (target, key) => {
  if (key === 'clearRect') return () => renders++;
  if (key === 'getImageData') return () => {throw Error('Unexpected pixel readback');};
  return target[key] || (() => {});
}, set: (target, key, value) => {target[key] = value; return true;}});
function element() {return {width:800,height:600,clientWidth:800,clientHeight:600,value:'',style:{},classList:{toggle(){},remove(){}},addEventListener(){},getContext:()=>context2d,getBoundingClientRect:()=>({left:0,top:0}),setPointerCapture(){}};}
const elements = new Map();
const sandbox = {assert,console,structuredClone,devicePixelRatio:1,Image:class {complete=true;width=2176;height=1696;},document:{querySelector(key){if(!elements.has(key))elements.set(key,element());return elements.get(key);},querySelectorAll:()=>[],createElement:element,addEventListener(){}},window:{addEventListener(){}},requestAnimationFrame:callback=>frames.push(callback)};
vm.createContext(sandbox);
vm.runInContext(script,sandbox);
vm.runInContext('for(let i=0;i<1000;i++)draw()',sandbox);
assert.equal(frames.length,1,'1000 drawing requests coalesce into one frame');
frames.shift()();
assert.equal(renders,1);
vm.runInContext(`
const seat={x:40,y:40,direction:'down'};
const first=seatPreview(seat);
assert.strictEqual(seatPreview(seat),first,'unchanged previews are reused');
seat.visible=Array.from({length:48},()=> '1'.repeat(32));
seat.visible[0]='0'.repeat(32);
const masked=seatPreview(seat);
assert.notStrictEqual(masked,first,'mask changes invalidate preview');
assert.strictEqual(seatPreview(seat),masked);
seat.direction='left';
assert.notStrictEqual(seatPreview(seat),masked,'direction changes invalidate preview');
state.points=[seat];state.selected=0;state.scale=24;state.brushSize=2;
remember();
paintAvatarLine({x:-1000000,y:43},{x:1000000,y:43},false);
assert.equal(seat.visible[24],'0'.repeat(32),'fast stroke has no gaps');
const painted=JSON.stringify(seat.visible);
undo();assert.notEqual(JSON.stringify(state.points[0].visible),painted);
redo();assert.equal(JSON.stringify(state.points[0].visible),painted);
seatMapData={version:1,seats:[]};
assert.equal(mapSeats().seats[0].visible[24],'0'.repeat(32),'export retains edited mask');
assert.equal(clipLine({x:-5,y:-5},{x:-1,y:-1},0,0,32,48),null);
collisionMap={width:10,height:10,tileWidth:16,tileHeight:16,data:Array(100).fill(0)};
paintCollisionLine({x:-1000000,y:8},{x:1000000,y:8},1);
assert.equal(collisionMap.data.slice(0,10).reduce((a,b)=>a+b,0),10,'collision stroke is clipped without gaps');
assert.equal(collisionMap.data.slice(10).reduce((a,b)=>a+b,0),0);
avatarReady=true;state.points=[{x:100000,y:100000,direction:'down'}];
render();assert.equal(avatarPreviews.has(state.points[0]),false,'offscreen seats do not create previews');
`,sandbox);
assert.equal(frames.length,1,'painting and history updates still request only one frame');
console.log('SeatMapper checks passed: frame batching, preview cache/invalidation, continuous masks, undo/redo, export, clipped collision strokes, offscreen culling.');
